INSERT INTO CATEGORY (CATEGORY_ID,CATEGORY_NAME,CATEGORY_SHORT_DSC,CATEGORY_DSC,BANNER_IMG) VALUES (CATEGORY_SEQ.nextval,'Programming Language',null,null,null);
INSERT INTO CATEGORY (CATEGORY_ID,CATEGORY_NAME,CATEGORY_SHORT_DSC,CATEGORY_DSC,BANNER_IMG) VALUES (CATEGORY_SEQ.nextval,'Big Data',null,null,null);
INSERT INTO CATEGORY (CATEGORY_ID,CATEGORY_NAME,CATEGORY_SHORT_DSC,CATEGORY_DSC,BANNER_IMG) VALUES (CATEGORY_SEQ.nextval,'Cloud Computing',null,null,null);
INSERT INTO CATEGORY (CATEGORY_ID,CATEGORY_NAME,CATEGORY_SHORT_DSC,CATEGORY_DSC,BANNER_IMG) VALUES (CATEGORY_SEQ.nextval,'Enterprise Content Managemen',null,null,null);
INSERT INTO CATEGORY (CATEGORY_ID,CATEGORY_NAME,CATEGORY_SHORT_DSC,CATEGORY_DSC,BANNER_IMG) VALUES (CATEGORY_SEQ.nextval,'GIS',null,null,null);
INSERT INTO CATEGORY (CATEGORY_ID,CATEGORY_NAME,CATEGORY_SHORT_DSC,CATEGORY_DSC,BANNER_IMG) VALUES (CATEGORY_SEQ.nextval,'IT and Hardware',null,null,null);
INSERT INTO CATEGORY (CATEGORY_ID,CATEGORY_NAME,CATEGORY_SHORT_DSC,CATEGORY_DSC,BANNER_IMG) VALUES (CATEGORY_SEQ.nextval,'Network Administration',null,null,null);
INSERT INTO CATEGORY (CATEGORY_ID,CATEGORY_NAME,CATEGORY_SHORT_DSC,CATEGORY_DSC,BANNER_IMG) VALUES (CATEGORY_SEQ.nextval,'Operating System',null,null,null);
INSERT INTO CATEGORY (CATEGORY_ID,CATEGORY_NAME,CATEGORY_SHORT_DSC,CATEGORY_DSC,BANNER_IMG) VALUES (CATEGORY_SEQ.nextval,'DBMS',null,null,null);
INSERT INTO CATEGORY (CATEGORY_ID,CATEGORY_NAME,CATEGORY_SHORT_DSC,CATEGORY_DSC,BANNER_IMG) VALUES (CATEGORY_SEQ.nextval,'Programming Languages',null,null,null);
INSERT INTO CATEGORY (CATEGORY_ID,CATEGORY_NAME,CATEGORY_SHORT_DSC,CATEGORY_DSC,BANNER_IMG) VALUES (CATEGORY_SEQ.nextval,'Business Intelligence',null,null,null);
INSERT INTO CATEGORY (CATEGORY_ID,CATEGORY_NAME,CATEGORY_SHORT_DSC,CATEGORY_DSC,BANNER_IMG) VALUES (CATEGORY_SEQ.nextval,'Internet Fundamentals',null,null,null);
INSERT INTO CATEGORY (CATEGORY_ID,CATEGORY_NAME,CATEGORY_SHORT_DSC,CATEGORY_DSC,BANNER_IMG) VALUES (CATEGORY_SEQ.nextval,'Networking',null,null,null);
INSERT INTO CATEGORY (CATEGORY_ID,CATEGORY_NAME,CATEGORY_SHORT_DSC,CATEGORY_DSC,BANNER_IMG) VALUES (CATEGORY_SEQ.nextval,'Security',null,null,null);
commit;

INSERT INTO TYPE (TYPE_ID,TYPE_DSC) VALUES (type_seq.nextval,'External Course');  
INSERT INTO TYPE (TYPE_ID,TYPE_DSC) VALUES (type_seq.nextval,'Book');  
INSERT INTO TYPE (TYPE_ID,TYPE_DSC) VALUES (type_seq.nextval,'Onsite Course');  

commit;
          
