DROP SEQUENCE category_seq;
DROP SEQUENCE contact_us_seq ;
DROP SEQUENCE resource_seq ;
DROP SEQUENCE type_seq ;

CREATE SEQUENCE category_seq INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE contact_us_seq INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE resource_seq INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE type_seq INCREMENT BY 1 NOCACHE NOCYCLE;
