CREATE SEQUENCE category_seq INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE contact_us_seq INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE resource_seq INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE type_seq INCREMENT BY 1 NOCACHE NOCYCLE;